[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "impacket>=0.12.0",
    "paramiko>=3.5.1",
    "requests>=2.32.4",
    "scapy>=2.6.1",
]
